# Generated by Django 6.0.2 on 2026-02-08 14:10

from django.db import migrations

def seed_permissions(apps, schema_editor):
    Permission = apps.get_model("access", "Permission")

    from access.permissions import iter_permissions

    for key, desc in iter_permissions():
        Permission.objects.update_or_create(
            key=key,
            defaults={"description": desc},
        )

class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_permissions),
    ]
