# Generated by Django 6.0.2 on 2026-02-11 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_seed_permissions'),
        ('companies', '0002_alter_company_date_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='key',
            field=models.CharField(help_text='System permission key (e.g. "roles.create").', max_length=120, unique=True),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'is_active'], name='idx_membership_user_active'),
        ),
    ]
