/**
 * Brutalist component defaults — shared between light and dark presets.
 *
 * These structural values (shape, border, spacing, motion) are mode-agnostic:
 * the same sharp, flat, no-decoration baseline applies in both themes.
 * Color values are defined separately in each preset.
 */
import type { ThemeTokens } from "../types";

export const componentDefaults: Pick<
  ThemeTokens,
  | "btnRadius"
  | "btnBorderTop"
  | "btnBorderRight"
  | "btnBorderBottom"
  | "btnBorderLeft"
  | "btnBorderStyle"
  | "btnFontWeight"
  | "btnLetterSpacing"
  | "btnTextTransform"
  | "btnShadow"
  | "btnHoverTransform"
  | "btnHoverFilter"
  | "btnPressScale"
  | "btnTransitionDuration"
  | "btnRotateX"
  | "btnRotateY"
  | "btnRotateZ"
  | "btnHoverRotateX"
  | "btnHoverRotateY"
  | "btnHoverRotateZ"
  | "btnCursorTrack"
  | "btnCursorTrackRestore"
  | "inputRadius"
  | "inputBorderTop"
  | "inputBorderRight"
  | "inputBorderBottom"
  | "inputBorderLeft"
  | "inputBorderStyle"
  | "inputLabelWeight"
  | "inputLabelSize"
  | "inputShadow"
  | "inputPaddingX"
  | "inputPaddingY"
  | "inputFontSize"
  | "inputPlaceholderOpacity"
  | "inputFocusRingWidth"
  | "inputFocusRingOffset"
  | "inputTransitionDuration"
  | "inputTextAlign"
  | "cardRadius"
  | "cardBorderTop"
  | "cardBorderRight"
  | "cardBorderBottom"
  | "cardBorderLeft"
  | "cardBorderStyle"
  | "cardShadow"
  | "cardRotateX"
  | "cardRotateY"
  | "cardRotateZ"
  | "cardHoverRotateX"
  | "cardHoverRotateY"
  | "cardHoverRotateZ"
  | "cardHoverTranslateY"
  | "cardHoverScale"
  | "cardTransitionDuration"
  | "cardCursorTrack"
  | "cardCursorTrackRestore"
  | "badgeRadius"
  | "badgeBorderTop"
  | "badgeBorderRight"
  | "badgeBorderBottom"
  | "badgeBorderLeft"
  | "badgeBorderStyle"
  | "badgeFontWeight"
  | "badgeFontSize"
  | "badgeLetterSpacing"
  | "badgeTextTransform"
  | "badgePaddingX"
  | "badgePaddingY"
  | "badgeRotateX"
  | "badgeRotateY"
  | "badgeRotateZ"
  | "badgeHoverRotateX"
  | "badgeHoverRotateY"
  | "badgeHoverRotateZ"
  | "badgeHoverTranslateY"
  | "badgeHoverScale"
  | "badgeTransitionDuration"
  | "badgeCursorTrack"
  | "badgeCursorTrackRestore"
  | "accordionRadius"
  | "accordionBorderWidth"
  | "accordionBorderStyle"
  | "accordionSeparatorHeight"
  | "accordionTriggerPaddingX"
  | "accordionTriggerPaddingY"
  | "accordionTriggerFontWeight"
  | "accordionTriggerFontSize"
  | "accordionContentPaddingX"
  | "accordionContentPaddingY"
  | "accordionShadow"
  | "alertRadius"
  | "alertBorderWidth"
  | "alertBorderStyle"
  | "alertPaddingX"
  | "alertPaddingY"
  | "alertTitleFontWeight"
  | "alertTitleFontSize"
  | "alertDescriptionFontSize"
  | "alertIconSize"
  | "alertShadow"
  | "alertDialogRadius"
  | "alertDialogPaddingX"
  | "alertDialogPaddingY"
  | "alertDialogShadow"
  | "alertDialogBackdropBlur"
  | "alertDialogBackdropColor"
  | "alertDialogBackdropOpacity"
  | "autocompletePopoverRadius"
  | "autocompletePopoverBorderTop"
  | "autocompletePopoverBorderRight"
  | "autocompletePopoverBorderBottom"
  | "autocompletePopoverBorderLeft"
  | "autocompletePopoverBorderStyle"
  | "autocompletePopoverShadow"
  | "autocompletePopoverPadding"
  | "autocompleteItemPaddingX"
  | "autocompleteItemPaddingY"
  | "autocompleteItemFontSize"
  | "autocompleteItemRadius"
  | "autocompleteItemDivider"
  | "autocompleteMaxHeight"
  | "avatarRadius"
  | "avatarBorderTop"
  | "avatarBorderRight"
  | "avatarBorderBottom"
  | "avatarBorderLeft"
  | "avatarBorderStyle"
  | "avatarSizeSm"
  | "avatarSizeMd"
  | "avatarSizeLg"
  | "avatarFallbackFontWeight"
  | "avatarFallbackFontSize"
  | "avatarGroupSpacing"
  | "avatarRotateX"
  | "avatarRotateY"
  | "avatarRotateZ"
  | "avatarHoverRotateX"
  | "avatarHoverRotateY"
  | "avatarHoverRotateZ"
  | "avatarHoverTranslateY"
  | "avatarHoverScale"
  | "avatarTransitionDuration"
  | "avatarCursorTrack"
  | "avatarCursorTrackRestore"
  | "breadcrumbsFontSize"
  | "breadcrumbsFontWeight"
  | "breadcrumbsActiveFontWeight"
  | "breadcrumbsLetterSpacing"
  | "breadcrumbsTextTransform"
  | "breadcrumbsGap"
  | "breadcrumbsItemPaddingX"
  | "breadcrumbsItemPaddingY"
  | "breadcrumbsItemRadius"
  | "breadcrumbsItemBorderWidth"
  | "breadcrumbsItemBorderStyle"
  | "breadcrumbsSeparatorIcon"
  | "breadcrumbsSeparatorSize"
  | "breadcrumbsSeparatorOpacity"
  | "breadcrumbsUnderline"
  | "buttonGroupGap"
  | "buttonGroupBorderTop"
  | "buttonGroupBorderRight"
  | "buttonGroupBorderBottom"
  | "buttonGroupBorderLeft"
  | "buttonGroupBorderStyle"
  | "buttonGroupShadow"
  | "calendarRadius"
  | "calendarBorderTop"
  | "calendarBorderRight"
  | "calendarBorderBottom"
  | "calendarBorderLeft"
  | "calendarBorderStyle"
  | "calendarShadow"
  | "calendarRotateX"
  | "calendarRotateY"
  | "calendarRotateZ"
  | "calendarHoverRotateX"
  | "calendarHoverRotateY"
  | "calendarHoverRotateZ"
  | "calendarHoverTranslateY"
  | "calendarHoverScale"
  | "calendarTransitionDuration"
  | "calendarCursorTrack"
  | "calendarCursorTrackRestore"
  | "checkboxSize"
  | "checkboxRadius"
  | "checkboxBorderWidth"
  | "checkboxBorderStyle"
  | "checkboxGap"
  | "checkboxLabelFontSize"
  | "checkboxLabelFontWeight"
  | "checkboxShadow"
  | "checkboxCheckedScale"
  | "checkboxTransitionDuration"
  | "checkboxIndicatorSize"
  | "checkboxIndicatorStroke"
  | "checkboxGroupGap"
  | "checkboxGroupRadius"
  | "checkboxGroupPaddingX"
  | "checkboxGroupPaddingY"
  | "checkboxGroupBorderWidth"
  | "checkboxGroupBorderStyle"
  | "checkboxGroupShadow"
  | "checkboxGroupLabelFontSize"
  | "checkboxGroupLabelFontWeight"
  | "checkboxGroupLabelGap"
  | "colorPickerPopoverRadius"
  | "colorPickerPopoverShadow"
  | "colorPickerPopoverPadding"
  | "colorPickerPopoverBorderWidth"
  | "colorPickerPopoverBorderStyle"
  | "colorPickerSwatchRadius"
  | "colorPickerSwatchSize"
  | "colorPickerSwatchGap"
  | "colorPickerSwatchBorderWidth"
  | "colorPickerSliderRadius"
  | "colorPickerSliderHeight"
  | "colorPickerThumbSize"
  | "colorPickerThumbBorderWidth"
  | "colorPickerAreaRadius"
  | "colorPickerTransitionDuration"
  | "comboBoxPopoverRadius"
  | "comboBoxPopoverShadow"
  | "comboBoxPopoverPadding"
  | "comboBoxPopoverBorderWidth"
  | "comboBoxPopoverBorderStyle"
  | "comboBoxTriggerRadius"
  | "comboBoxTriggerBorderWidth"
  | "comboBoxItemPaddingX"
  | "comboBoxItemPaddingY"
  | "comboBoxItemFontSize"
  | "comboBoxItemRadius"
  | "comboBoxTransitionDuration"
  | "datePickerTriggerRadius"
  | "datePickerTriggerBorderWidth"
  | "datePickerTriggerBorderStyle"
  | "datePickerTriggerPaddingX"
  | "datePickerTriggerPaddingY"
  | "datePickerTriggerShadow"
  | "datePickerPopoverRadius"
  | "datePickerPopoverShadow"
  | "datePickerPopoverPadding"
  | "datePickerIndicatorSize"
  | "datePickerTransitionDuration"
  | "tabsListRadius"
  | "tabsListPadding"
  | "tabsListGap"
  | "tabsTabRadius"
  | "tabsTabPaddingX"
  | "tabsTabPaddingY"
  | "tabsTabFontSize"
  | "tabsTabFontWeight"
  | "tabsPanelPadding"
  | "tabsTransitionDuration"
  | "tabsRotateX"
  | "tabsRotateY"
  | "tabsRotateZ"
  | "tabsHoverRotateX"
  | "tabsHoverRotateY"
  | "tabsHoverRotateZ"
  | "tabsHoverTranslateY"
  | "tabsHoverScale"
  | "sliderTrackHeight"
  | "sliderTrackRadius"
  | "sliderThumbSize"
  | "sliderThumbDotSize"
  | "sliderThumbRadius"
  | "sliderThumbShadow"
  | "sliderTransitionDuration"
  | "sliderRotateX"
  | "sliderRotateY"
  | "sliderRotateZ"
  | "sliderHoverRotateX"
  | "sliderHoverRotateY"
  | "sliderHoverRotateZ"
  | "sliderHoverTranslateY"
  | "sliderHoverScale"
  | "spinnerSizeSm"
  | "spinnerSizeMd"
  | "spinnerSizeLg"
  | "spinnerRotateX"
  | "spinnerRotateY"
  | "spinnerRotateZ"
  | "skeletonRadius"
  | "skeletonBaseColor"
  | "skeletonAnimationDuration"
  | "separatorThickness"
  | "separatorRadius"
  | "selectRadius"
  | "selectBorderWidth"
  | "modalRadius"
> = {
  // Button — sharp, flat, no decorative radius or shadow
  btnRadius: "0px",
  btnBorderTop: "1px",
  btnBorderRight: "1px",
  btnBorderBottom: "1px",
  btnBorderLeft: "1px",
  btnBorderStyle: "solid",
  btnFontWeight: "500",
  btnLetterSpacing: "0.02em",
  btnTextTransform: "none",
  btnShadow: "none",
  btnHoverTransform: "",
  btnHoverFilter: "none",
  btnPressScale: "0.97",
  btnTransitionDuration: "150ms",
  btnRotateX: "0deg",
  btnRotateY: "0deg",
  btnRotateZ: "0deg",
  btnHoverRotateX: "",
  btnHoverRotateY: "",
  btnHoverRotateZ: "",
  btnCursorTrack: "0",
  btnCursorTrackRestore: "300ms",

  // Input
  inputRadius: "0px",
  inputBorderTop: "1px",
  inputBorderRight: "1px",
  inputBorderBottom: "1px",
  inputBorderLeft: "1px",
  inputBorderStyle: "solid",
  inputLabelWeight: "500",
  inputLabelSize: "12px",
  inputShadow: "none",
  inputPaddingX: "12px",
  inputPaddingY: "8px",
  inputFontSize: "14px",
  inputPlaceholderOpacity: "0.45",
  inputFocusRingWidth: "2px",
  inputFocusRingOffset: "0px",
  inputTransitionDuration: "150ms",
  inputTextAlign: "left",

  // Card
  cardRadius: "0px",
  cardBorderTop: "1px",
  cardBorderRight: "1px",
  cardBorderBottom: "1px",
  cardBorderLeft: "1px",
  cardBorderStyle: "solid",
  cardShadow: "none",
  cardRotateX: "0deg",
  cardRotateY: "0deg",
  cardRotateZ: "0deg",
  cardHoverRotateX: "",
  cardHoverRotateY: "",
  cardHoverRotateZ: "",
  cardHoverTranslateY: "0px",
  cardHoverScale: "1",
  cardTransitionDuration: "150ms",
  cardCursorTrack: "0",
  cardCursorTrackRestore: "300ms",

  // Badge
  badgeRadius: "0px",
  badgeBorderTop: "1px",
  badgeBorderRight: "1px",
  badgeBorderBottom: "1px",
  badgeBorderLeft: "1px",
  badgeBorderStyle: "solid",
  badgeFontWeight: "600",
  badgeFontSize: "0.6875rem",
  badgeLetterSpacing: "0em",
  badgeTextTransform: "none",
  badgePaddingX: "0.55rem",
  badgePaddingY: "0.2rem",
  badgeRotateX: "0deg",
  badgeRotateY: "0deg",
  badgeRotateZ: "0deg",
  badgeHoverRotateX: "",
  badgeHoverRotateY: "",
  badgeHoverRotateZ: "",
  badgeHoverTranslateY: "0px",
  badgeHoverScale: "1",
  badgeTransitionDuration: "150ms",
  badgeCursorTrack: "0",
  badgeCursorTrackRestore: "300ms",

  // Accordion
  accordionRadius: "0px",
  accordionBorderWidth: "1px",
  accordionBorderStyle: "solid",
  accordionSeparatorHeight: "1px",
  accordionTriggerPaddingX: "16px",
  accordionTriggerPaddingY: "12px",
  accordionTriggerFontWeight: "500",
  accordionTriggerFontSize: "14px",
  accordionContentPaddingX: "16px",
  accordionContentPaddingY: "8px",
  accordionShadow: "none",

  // Alert
  alertRadius: "0px",
  alertBorderWidth: "1px",
  alertBorderStyle: "solid",
  alertPaddingX: "16px",
  alertPaddingY: "12px",
  alertTitleFontWeight: "600",
  alertTitleFontSize: "14px",
  alertDescriptionFontSize: "13px",
  alertIconSize: "20px",
  alertShadow: "none",

  // Alert Dialog
  alertDialogRadius: "0px",
  alertDialogPaddingX: "24px",
  alertDialogPaddingY: "20px",
  alertDialogShadow: "none",
  alertDialogBackdropBlur: "0px",
  alertDialogBackdropColor: "oklch(0 0 0 / 0.4)",
  alertDialogBackdropOpacity: "1",

  // Autocomplete
  autocompletePopoverRadius: "0px",
  autocompletePopoverBorderTop: "1px",
  autocompletePopoverBorderRight: "1px",
  autocompletePopoverBorderBottom: "1px",
  autocompletePopoverBorderLeft: "1px",
  autocompletePopoverBorderStyle: "solid",
  autocompletePopoverShadow: "none",
  autocompletePopoverPadding: "4px",
  autocompleteItemPaddingX: "12px",
  autocompleteItemPaddingY: "8px",
  autocompleteItemFontSize: "14px",
  autocompleteItemRadius: "0px",
  autocompleteItemDivider: "0px",
  autocompleteMaxHeight: "256px",

  // Avatar
  avatarRadius: "9999px",
  avatarBorderTop: "0px",
  avatarBorderRight: "0px",
  avatarBorderBottom: "0px",
  avatarBorderLeft: "0px",
  avatarBorderStyle: "solid",
  avatarSizeSm: "32px",
  avatarSizeMd: "40px",
  avatarSizeLg: "48px",
  avatarFallbackFontWeight: "600",
  avatarFallbackFontSize: "14px",
  avatarGroupSpacing: "-8px",
  avatarRotateX: "0deg",
  avatarRotateY: "0deg",
  avatarRotateZ: "0deg",
  avatarHoverRotateX: "",
  avatarHoverRotateY: "",
  avatarHoverRotateZ: "",
  avatarHoverTranslateY: "0px",
  avatarHoverScale: "1",
  avatarTransitionDuration: "150ms",
  avatarCursorTrack: "0",
  avatarCursorTrackRestore: "300ms",

  // Breadcrumbs
  breadcrumbsFontSize: "14px",
  breadcrumbsFontWeight: "400",
  breadcrumbsActiveFontWeight: "600",
  breadcrumbsLetterSpacing: "0em",
  breadcrumbsTextTransform: "none",
  breadcrumbsGap: "8px",
  breadcrumbsItemPaddingX: "0px",
  breadcrumbsItemPaddingY: "0px",
  breadcrumbsItemRadius: "0px",
  breadcrumbsItemBorderWidth: "0px",
  breadcrumbsItemBorderStyle: "solid",
  breadcrumbsSeparatorIcon: "chevron-right",
  breadcrumbsSeparatorSize: "16px",
  breadcrumbsSeparatorOpacity: "0.5",
  breadcrumbsUnderline: "none",

  // ButtonGroup
  buttonGroupGap: "0px",
  buttonGroupBorderTop: "0px",
  buttonGroupBorderRight: "1px",
  buttonGroupBorderBottom: "1px",
  buttonGroupBorderLeft: "1px",
  buttonGroupBorderStyle: "solid",
  buttonGroupShadow: "none",

  // Calendar
  calendarRadius: "0px",
  calendarBorderTop: "1px",
  calendarBorderRight: "1px",
  calendarBorderBottom: "1px",
  calendarBorderLeft: "1px",
  calendarBorderStyle: "solid",
  calendarShadow: "none",
  calendarRotateX: "0deg",
  calendarRotateY: "0deg",
  calendarRotateZ: "0deg",
  calendarHoverRotateX: "",
  calendarHoverRotateY: "",
  calendarHoverRotateZ: "",
  calendarHoverTranslateY: "0px",
  calendarHoverScale: "1",
  calendarTransitionDuration: "150ms",
  calendarCursorTrack: "0",
  calendarCursorTrackRestore: "300ms",
  // Checkbox
  checkboxSize: "20px",
  checkboxRadius: "4px",
  checkboxBorderWidth: "2px",
  checkboxBorderStyle: "solid",
  checkboxGap: "8px",
  checkboxLabelFontSize: "14px",
  checkboxLabelFontWeight: "400",
  checkboxShadow: "none",
  checkboxCheckedScale: "0.95",
  checkboxTransitionDuration: "150ms",
  checkboxIndicatorSize: "12px",
  checkboxIndicatorStroke: "2.5",

  // Checkbox Group
  checkboxGroupGap: "10px",
  checkboxGroupRadius: "0px",
  checkboxGroupPaddingX: "0px",
  checkboxGroupPaddingY: "0px",
  checkboxGroupBorderWidth: "0px",
  checkboxGroupBorderStyle: "solid",
  checkboxGroupShadow: "none",
  checkboxGroupLabelFontSize: "14px",
  checkboxGroupLabelFontWeight: "500",
  checkboxGroupLabelGap: "8px",

  // Color Picker
  colorPickerPopoverRadius: "8px",
  colorPickerPopoverShadow: "0 4px 14px oklch(0 0 0 / 0.1)",
  colorPickerPopoverPadding: "16px",
  colorPickerPopoverBorderWidth: "1px",
  colorPickerPopoverBorderStyle: "solid",
  colorPickerSwatchRadius: "6px",
  colorPickerSwatchSize: "28px",
  colorPickerSwatchGap: "6px",
  colorPickerSwatchBorderWidth: "2px",
  colorPickerSliderRadius: "9999px",
  colorPickerSliderHeight: "12px",
  colorPickerThumbSize: "18px",
  colorPickerThumbBorderWidth: "2px",
  colorPickerAreaRadius: "8px",
  colorPickerTransitionDuration: "150ms",

  // ComboBox
  comboBoxPopoverRadius: "0px",
  comboBoxPopoverShadow: "none",
  comboBoxPopoverPadding: "4px",
  comboBoxPopoverBorderWidth: "1px",
  comboBoxPopoverBorderStyle: "solid",
  comboBoxTriggerRadius: "0px",
  comboBoxTriggerBorderWidth: "1px",
  comboBoxItemPaddingX: "12px",
  comboBoxItemPaddingY: "8px",
  comboBoxItemFontSize: "14px",
  comboBoxItemRadius: "0px",
  comboBoxTransitionDuration: "150ms",

  // DatePicker
  datePickerTriggerRadius: "0px",
  datePickerTriggerBorderWidth: "1px",
  datePickerTriggerBorderStyle: "solid",
  datePickerTriggerPaddingX: "12px",
  datePickerTriggerPaddingY: "8px",
  datePickerTriggerShadow: "none",
  datePickerPopoverRadius: "0px",
  datePickerPopoverShadow: "none",
  datePickerPopoverPadding: "12px",
  datePickerIndicatorSize: "18px",
  datePickerTransitionDuration: "150ms",

  // Tabs
  tabsListRadius: "12px",
  tabsListPadding: "4px",
  tabsListGap: "0px",
  tabsTabRadius: "8px",
  tabsTabPaddingX: "12px",
  tabsTabPaddingY: "6px",
  tabsTabFontSize: "14px",
  tabsTabFontWeight: "500",
  tabsPanelPadding: "12px",
  tabsTransitionDuration: "200ms",
  tabsRotateX: "0deg",
  tabsRotateY: "0deg",
  tabsRotateZ: "0deg",
  tabsHoverRotateX: "",
  tabsHoverRotateY: "",
  tabsHoverRotateZ: "",
  tabsHoverTranslateY: "0px",
  tabsHoverScale: "1",

  // Slider
  sliderTrackHeight: "6px",
  sliderTrackRadius: "9999px",
  sliderThumbSize: "20px",
  sliderThumbDotSize: "16px",
  sliderThumbRadius: "9999px",
  sliderThumbShadow: "0 1px 3px oklch(0 0 0 / 0.15)",
  sliderTransitionDuration: "150ms",
  sliderRotateX: "0deg",
  sliderRotateY: "0deg",
  sliderRotateZ: "0deg",
  sliderHoverRotateX: "",
  sliderHoverRotateY: "",
  sliderHoverRotateZ: "",
  sliderHoverTranslateY: "0px",
  sliderHoverScale: "1",

  // Spinner
  spinnerSizeSm: "20px",
  spinnerSizeMd: "32px",
  spinnerSizeLg: "48px",
  spinnerRotateX: "0deg",
  spinnerRotateY: "0deg",
  spinnerRotateZ: "0deg",

  // Skeleton
  skeletonRadius: "8px",
  skeletonBaseColor: "var(--vita-neutral-200)",
  skeletonAnimationDuration: "1.5s",

  // Separator
  separatorThickness: "1px",
  separatorRadius: "0px",

  // Select
  selectRadius: "0px",
  selectBorderWidth: "1px",

  // Modal
  modalRadius: "0px",
};
