# Generated by Django 6.0.2 on 2026-02-15 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_seed_units_of_measure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=500)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='items.item')),
            ],
            options={
                'verbose_name': 'Item Attribute',
                'verbose_name_plural': 'Item Attributes',
                'db_table': 'item_attributes',
                'ordering': ['key'],
                'constraints': [models.UniqueConstraint(fields=('item', 'key'), name='uniq_attribute_key_per_item')],
            },
        ),
    ]
