# Generated by Django 6.0.2 on 2026-02-15 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('address_type', models.CharField(choices=[('headquarters', 'Headquarters'), ('warehouse', 'Warehouse'), ('billing', 'Billing'), ('other', 'Other')], default='headquarters', max_length=20)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Address',
                'verbose_name_plural': 'Supplier Addresses',
                'db_table': 'supplier_addresses',
                'ordering': ['-is_primary', 'address_type'],
            },
        ),
    ]
