# Generated by Django 6.0.2 on 2026-02-11 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0003_alter_permission_key_and_more'),
        ('companies', '0002_alter_company_date_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_email', models.EmailField(help_text='Email address of the person being invited', max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Invitation expiration date')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='', help_text='Optional message from inviter', max_length=500)),
                ('company', models.ForeignKey(help_text='Company the user is being invited to', on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='companies.company')),
                ('invitee_user', models.ForeignKey(blank=True, help_text='User account if invitee is already registered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_invites', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(help_text='User who sent the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(help_text='Role to assign when invitation is accepted', on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='access.role')),
            ],
            options={
                'verbose_name': 'Invite',
                'verbose_name_plural': 'Invites',
                'db_table': 'invites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invitee_email', 'status'], name='idx_invite_email_status'), models.Index(fields=['company', 'status'], name='idx_invite_company_status')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('company', 'invitee_email', 'status'), name='uniq_pending_invite_per_email_company')],
            },
        ),
    ]
