# Generated by Django 5.2.12 on 2026-03-29 18:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(help_text='References accounts.User.id in the central DB.')),
                ('action', models.CharField(help_text="Action identifier (e.g., 'role_created', 'item_updated').", max_length=50)),
                ('entity_type', models.CharField(blank=True, help_text="Model or entity type (e.g., 'Role', 'Item', 'ManufacturingOrder').", max_length=100)),
                ('entity_id', models.CharField(blank=True, help_text='Primary key of the affected record.', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='audit_log_user_id_4dac76_idx'), models.Index(fields=['action'], name='audit_log_action_b32d4d_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_log_entity__c2633a_idx'), models.Index(fields=['created_at'], name='audit_log_created_5a7975_idx')],
            },
        ),
    ]
