# Generated by Django 5.2.12 on 2026-03-29 18:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('module_code', models.CharField(blank=True, help_text='Module this add-on extends. Blank = platform-wide (e.g., priority support).', max_length=50)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_annual', models.DecimalField(decimal_places=2, default=0, help_text='Annual price (typically discounted vs 12× monthly).', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive add-ons cannot be newly activated.')),
                ('stripe_product_id', models.CharField(blank=True, max_length=255)),
                ('stripe_price_id_monthly', models.CharField(blank=True, max_length=255)),
                ('stripe_price_id_annual', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'billing_add_on',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('base_price_monthly', models.DecimalField(decimal_places=2, default=0, help_text='Flat monthly fee for the platform itself.', max_digits=10)),
                ('base_price_annual', models.DecimalField(decimal_places=2, default=0, help_text='Flat annual fee (typically discounted vs 12× monthly).', max_digits=10)),
                ('is_trial', models.BooleanField(default=False, help_text='Whether this plan is used for free trial subscriptions.')),
                ('trial_duration_days', models.PositiveIntegerField(blank=True, help_text='Trial length in days. Only relevant when is_trial=True.', null=True)),
                ('is_public', models.BooleanField(default=True, help_text='Whether this plan is visible on the pricing page.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order on pricing page. Lower = first.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive plans cannot be assigned to new subscriptions.')),
                ('stripe_product_id', models.CharField(blank=True, help_text='Stripe Product ID for this plan.', max_length=255)),
                ('stripe_price_id_monthly', models.CharField(blank=True, help_text='Stripe Price ID for the monthly base fee.', max_length=255)),
                ('stripe_price_id_annual', models.CharField(blank=True, help_text='Stripe Price ID for the annual base fee.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'billing_plan',
                'ordering': ['sort_order', 'base_price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('paused', 'Paused'), ('incomplete', 'Incomplete')], db_index=True, default='trialing', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('current_period_start', models.DateTimeField(blank=True, help_text='Start of the current billing period.', null=True)),
                ('current_period_end', models.DateTimeField(blank=True, help_text='End of the current billing period.', null=True)),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, help_text='When the subscription was canceled. Null = not canceled.', null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False, help_text='If True, subscription remains active until current_period_end.')),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='Stripe Subscription ID.', max_length=255)),
                ('stripe_customer_id', models.CharField(blank=True, help_text='Stripe Customer ID for this organization.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organizations.organization')),
                ('plan', models.ForeignKey(help_text='PROTECT prevents deleting a plan that has active subscriptions.', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
            ],
            options={
                'db_table': 'billing_subscription',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionAddOn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_subscription_item_id', models.CharField(blank=True, help_text='Stripe Subscription Item ID for this add-on.', max_length=255)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('add_on', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_activations', to='billing.addon')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_add_ons', to='billing.subscription')),
            ],
            options={
                'db_table': 'billing_subscription_add_on',
            },
        ),
        migrations.CreateModel(
            name='PermissionPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_code', models.CharField(help_text="Module identifier (e.g., 'inventory', 'accounting').", max_length=50)),
                ('action', models.CharField(help_text="Permission action (e.g., 'read', 'write', 'delete', 'export').", max_length=30)),
                ('price_monthly', models.DecimalField(decimal_places=4, default=0, help_text='Monthly cost when this permission is granted to a user.', max_digits=10)),
                ('plan', models.ForeignKey(help_text='Prices can differ per plan (e.g., Pro has different rates than Starter).', on_delete=django.db.models.deletion.CASCADE, related_name='permission_prices', to='billing.plan')),
            ],
            options={
                'db_table': 'billing_permission_price',
                'ordering': ['module_code', 'action'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'module_code', 'action'), name='unique_permission_price_per_plan')],
            },
        ),
        migrations.CreateModel(
            name='PlanLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('limit_code', models.CharField(help_text="Identifier for this limit (e.g., 'max_users', 'storage_gb', 'sessions_per_user').", max_length=50)),
                ('description', models.CharField(blank=True, help_text='Human-readable description of what this limit controls.', max_length=255)),
                ('included_quantity', models.DecimalField(decimal_places=4, default=0, help_text='Quantity included in the plan at no extra cost.', max_digits=15)),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=4, help_text='Hard cap. Null = no hard limit (unlimited overage allowed).', max_digits=15, null=True)),
                ('price_per_extra', models.DecimalField(decimal_places=4, default=0, help_text='Cost per unit above included_quantity per billing period.', max_digits=10)),
                ('per_org', models.BooleanField(default=True, help_text='True = org-wide limit (e.g., total storage). False = per-user limit (e.g., sessions).')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='billing.plan')),
            ],
            options={
                'db_table': 'billing_plan_limit',
                'ordering': ['limit_code'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'limit_code'), name='unique_limit_per_plan')],
            },
        ),
        migrations.CreateModel(
            name='PlanModuleAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_code', models.CharField(help_text="Module identifier (e.g., 'inventory', 'production').", max_length=50)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_access', to='billing.plan')),
            ],
            options={
                'db_table': 'billing_plan_module_access',
                'constraints': [models.UniqueConstraint(fields=('plan', 'module_code'), name='unique_module_per_plan')],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status'], name='billing_sub_status_948046_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['stripe_subscription_id'], name='billing_sub_stripe__abc269_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['stripe_customer_id'], name='billing_sub_stripe__97887e_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionaddon',
            constraint=models.UniqueConstraint(fields=('subscription', 'add_on'), name='unique_add_on_per_subscription'),
        ),
    ]
