# Generated by Django 5.2.12 on 2026-04-11 11:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_stripe_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('module_code', models.CharField(blank=True, help_text='Module this add-on extends. Blank = platform-wide (e.g., priority support).', max_length=50)),
                ('billing_type', models.CharField(choices=[('recurring', 'Recurring (monthly)'), ('one_time', 'One-time purchase')], default='recurring', help_text='Whether this add-on charges monthly or as a single one-off payment.', max_length=20)),
                ('price_pence', models.PositiveIntegerField(default=0, help_text='Price in pence. Monthly amount for recurring, total amount for one-time.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive add-ons are hidden in the UI and cannot be newly purchased.')),
                ('stripe_product_id', models.CharField(blank=True, max_length=255)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'billing_add_on',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BillingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_price_pence', models.PositiveIntegerField(default=19900, help_text='Flat monthly platform fee in pence. Default: 19900 (£199).')),
                ('storage_minimum_gb', models.PositiveIntegerField(default=10, help_text='Storage quota included in the base fee. Users cannot choose less than this.')),
                ('storage_price_per_gb_pence', models.PositiveIntegerField(default=200, help_text='Monthly price per GB of additional storage in pence. Default: 200 (£2/GB).')),
                ('trial_duration_days', models.PositiveIntegerField(default=14, help_text='Free trial length in days. Card is required upfront; Stripe auto-charges at trial end.')),
                ('currency', models.CharField(default='gbp', help_text='ISO 4217 code (lowercase, to match Stripe convention). Platform charges exclusively in this currency.', max_length=3)),
                ('stripe_product_id', models.CharField(blank=True, help_text='Stripe Product ID — created on first sync, shared across all three Prices.', max_length=255)),
                ('stripe_base_price_id', models.CharField(blank=True, help_text='Stripe Price ID for the flat recurring base fee.', max_length=255)),
                ('stripe_user_metered_price_id', models.CharField(blank=True, help_text='Stripe Price ID for the metered per-user line. Unit = 1 penny.', max_length=255)),
                ('stripe_storage_price_id', models.CharField(blank=True, help_text='Stripe Price ID for the per-GB storage line. Quantity on subscription = GB above minimum.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Billing config',
                'verbose_name_plural': 'Billing config',
                'db_table': 'billing_config',
            },
        ),
        migrations.CreateModel(
            name='PermissionPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_code', models.CharField(help_text="Module identifier matching apps.rbac.constants.MODULE_* (e.g., 'accounts', 'billing').", max_length=50)),
                ('action', models.CharField(help_text="Permission action matching apps.rbac.constants.ACTION_* (e.g., 'read', 'write', 'manage').", max_length=30)),
                ('price_pence', models.PositiveIntegerField(default=0, help_text='Monthly cost in pence when this permission is granted to a user.')),
                ('description', models.CharField(blank=True, help_text='Human-readable description shown in the billing breakdown UI.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'billing_permission_price',
                'ordering': ['module_code', 'action'],
                'constraints': [models.UniqueConstraint(fields=('module_code', 'action'), name='unique_permission_price')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('paused', 'Paused'), ('incomplete', 'Incomplete')], db_index=True, default='trialing', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('storage_quota_gb', models.PositiveIntegerField(default=10, help_text='Storage ceiling the org is paying for. Must be >= BillingConfig.storage_minimum_gb.')),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False, help_text='If True, subscription remains active until current_period_end then stops auto-renewing.')),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='Stripe Subscription ID. Empty until the subscription has been created in Stripe.', max_length=255)),
                ('stripe_base_item_id', models.CharField(blank=True, help_text='Stripe Subscription Item ID for the flat base-fee line.', max_length=255)),
                ('stripe_user_item_id', models.CharField(blank=True, help_text='Stripe Subscription Item ID for the metered per-user line.', max_length=255)),
                ('stripe_storage_item_id', models.CharField(blank=True, help_text='Stripe Subscription Item ID for the per-GB storage line.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organizations.organization')),
            ],
            options={
                'db_table': 'billing_subscription',
            },
        ),
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_event_id', models.CharField(help_text='Stripe `event.id` — used for idempotency.', max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, help_text='Stripe `event.type` (e.g., `customer.subscription.updated`).', max_length=100)),
                ('payload', models.JSONField(help_text='Raw Stripe event payload.')),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='received', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Populated if `status=failed`. Used to retry or debug.')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(blank=True, help_text='Subscription this event relates to, if resolvable. Null for account-level events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='billing.subscription')),
            ],
            options={
                'db_table': 'billing_event',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionAddOn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_subscription_item_id', models.CharField(blank=True, help_text='Stripe Subscription Item ID for this add-on line.', max_length=255)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('add_on', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_activations', to='billing.addon')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_add_ons', to='billing.subscription')),
            ],
            options={
                'db_table': 'billing_subscription_add_on',
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status'], name='billing_sub_status_948046_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['stripe_subscription_id'], name='billing_sub_stripe__abc269_idx'),
        ),
        migrations.AddIndex(
            model_name='billingevent',
            index=models.Index(fields=['event_type', 'status'], name='billing_eve_event_t_b60755_idx'),
        ),
        migrations.AddIndex(
            model_name='billingevent',
            index=models.Index(fields=['-received_at'], name='billing_eve_receive_4e85b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionaddon',
            constraint=models.UniqueConstraint(fields=('subscription', 'add_on'), name='unique_add_on_per_subscription'),
        ),
    ]
