# Generated by Django 5.2.12 on 2026-04-11 15:56

import apps.org_accounts.models.user_media_asset
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('definition', models.JSONField(default=dict, help_text='Form schema produced by the frontend form constructor. Mirrors `FormSchema` in form-constructor/types.ts.')),
                ('version', models.PositiveIntegerField(default=1, help_text='Bumps on every save. Stamped on submissions for migration tracking.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Onboarding form',
                'verbose_name_plural': 'Onboarding form',
                'db_table': 'org_accounts_onboarding_form',
            },
        ),
        migrations.CreateModel(
            name='OnboardingSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('membership_id', models.UUIDField(db_index=True, help_text='References organizations.Membership.id in the central DB.')),
                ('form_version', models.PositiveIntegerField(help_text='OnboardingForm.version at the time of this submission.')),
                ('responses', models.JSONField(default=dict, help_text='Flat dict keyed by form field name. Values are scalars or media references like {"type": "media", "asset_id": "..."}.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'org_accounts_onboarding_submission',
                'ordering': ['-updated_at'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['responses'], name='onboarding_responses_gin', opclasses=['jsonb_path_ops'])],
                'constraints': [models.UniqueConstraint(fields=('membership_id',), name='unique_submission_per_membership')],
            },
        ),
        migrations.CreateModel(
            name='UserMediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(help_text="Form field this asset is bound to (e.g. 'profile_photo').", max_length=100)),
                ('file', models.FileField(upload_to=apps.org_accounts.models.user_media_asset._onboarding_upload_path)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='org_accounts.onboardingsubmission')),
            ],
            options={
                'db_table': 'org_accounts_user_media_asset',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['submission', 'field_name'], name='org_account_submiss_150b78_idx')],
            },
        ),
    ]
