# Generated by Django 6.0.2 on 2026-02-08 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'A company with that name already exists.'}, help_text='Required. Enter the company’s full legal name. Must be unique.', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_company_name', message='Company name contains invalid characters.', regex="^[\\w\\s&.,'()+\\-\\/]+$")])),
                ('description', models.TextField(blank=True, default='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
                'ordering': ['-date_created'],
            },
        ),
    ]
