# Generated by Django 5.2.12 on 2026-03-29 18:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Display name (e.g., 'Owner', 'Warehouse Staff').", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False, help_text='System roles (Owner) cannot be deleted or renamed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rbac_role',
                'ordering': ['-is_system', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_code', models.CharField(help_text="Module identifier (e.g., 'inventory', 'production').", max_length=50)),
                ('action', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('delete', 'Delete'), ('export', 'Export')], help_text='Permission action (read, write, delete, export).', max_length=30)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='rbac.role')),
            ],
            options={
                'db_table': 'rbac_role_permission',
                'ordering': ['module_code', 'action'],
                'constraints': [models.UniqueConstraint(fields=('role', 'module_code', 'action'), name='unique_permission_per_role')],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(help_text='References accounts.User.id in the central DB.')),
                ('assigned_by', models.UUIDField(blank=True, help_text='User ID of who granted this role.', null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='rbac.role')),
            ],
            options={
                'db_table': 'rbac_user_role',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['user_id'], name='rbac_user_r_user_id_a9d836_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'role'), name='unique_user_role')],
            },
        ),
    ]
