# Generated by Django 5.2.12 on 2026-04-06 08:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganogramLayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nodes_layout', models.JSONField(default=dict, help_text='Map of role UUID → {x: float, y: float}. Example: {"<uuid>": {"x": 100, "y": 200}}')),
                ('edges', models.JSONField(default=list, help_text='List of visual connections between roles. Example: [{"source": "<uuid>", "target": "<uuid>"}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rbac_organogram_layout',
            },
        ),
    ]
