# Generated by Django 5.2.12 on 2026-04-11 15:56

import apps.accounts.models.invitation
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_auditlog'),
        ('organizations', '0003_membership_onboarding_completed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Lowercased on save. Recipient of the invite link.', max_length=254)),
                ('token', models.CharField(default=apps.accounts.models.invitation._default_token, editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(default=apps.accounts.models.invitation._default_expiry)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('pre_assigned_role_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organizations.organization')),
            ],
            options={
                'db_table': 'accounts_invitation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'accepted_at', 'revoked_at'], name='accounts_in_organiz_335ba4_idx'), models.Index(fields=['email'], name='accounts_in_email_571f5a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('accepted_at__isnull', True), ('revoked_at__isnull', True)), fields=('email', 'organization'), name='unique_pending_invitation_per_email_per_org')],
            },
        ),
    ]
