# Generated by Django 5.2.12 on 2026-03-31 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decimal_separator', models.CharField(choices=[('dot', 'dot'), ('comma', 'comma')], default='dot', max_length=10)),
                ('thousands_separator', models.CharField(choices=[('comma', 'comma'), ('dot', 'dot'), ('space', 'space'), ('apostrophe', 'apostrophe'), ('none', 'none')], default='comma', max_length=10)),
                ('digit_grouping', models.CharField(choices=[('standard', 'standard'), ('indian', 'indian'), ('none', 'none')], default='standard', max_length=10)),
                ('quantity_precision', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('price_precision', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('currency_precision', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('exchange_rate_precision', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('percentage_precision', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('weight_precision', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('currency_symbol_position', models.CharField(choices=[('before', 'before'), ('after', 'after')], default='before', max_length=10)),
                ('currency_spacing', models.BooleanField(default=False, help_text='Insert a space between the currency symbol and amount.')),
                ('negative_format', models.CharField(choices=[('minus_before', 'minus_before'), ('minus_after', 'minus_after'), ('parentheses', 'parentheses')], default='minus_before', max_length=15)),
                ('multi_currency_enabled', models.BooleanField(default=False)),
                ('rounding_method', models.CharField(choices=[('half_up', 'half_up'), ('half_even', 'half_even'), ('ceiling', 'ceiling'), ('floor', 'floor')], default='half_up', max_length=10)),
                ('cash_rounding_enabled', models.BooleanField(default=False)),
                ('cash_rounding_increment', models.DecimalField(choices=[('0.01', '0.01'), ('0.05', '0.05'), ('0.10', '0.10'), ('0.25', '0.25'), ('0.50', '0.50'), ('1.00', '1.00')], decimal_places=2, default='0.01', max_digits=4)),
                ('date_format', models.CharField(choices=[('YYYY-MM-DD', 'YYYY-MM-DD'), ('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('DD.MM.YYYY', 'DD.MM.YYYY'), ('YYYY/MM/DD', 'YYYY/MM/DD'), ('DD-MM-YYYY', 'DD-MM-YYYY')], default='YYYY-MM-DD', max_length=20)),
                ('time_format', models.CharField(choices=[('24h', '24h'), ('12h', '12h')], default='24h', max_length=3)),
                ('week_start_day', models.CharField(choices=[('monday', 'monday'), ('sunday', 'sunday'), ('saturday', 'saturday')], default='monday', max_length=10)),
                ('calendar_system', models.CharField(choices=[('gregorian', 'gregorian'), ('hijri', 'hijri'), ('thai_buddhist', 'thai_buddhist'), ('persian', 'persian'), ('japanese', 'japanese')], default='gregorian', max_length=15)),
                ('measurement_system', models.CharField(choices=[('metric', 'metric'), ('imperial', 'imperial')], default='metric', max_length=10)),
                ('default_weight_uom', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('mg', 'mg'), ('t', 't'), ('lb', 'lb'), ('oz', 'oz')], default='kg', max_length=5)),
                ('default_length_uom', models.CharField(choices=[('m', 'm'), ('cm', 'cm'), ('mm', 'mm'), ('ft', 'ft'), ('in', 'in'), ('yd', 'yd')], default='m', max_length=5)),
                ('default_volume_uom', models.CharField(choices=[('L', 'L'), ('mL', 'mL'), ('m3', 'm3'), ('gal', 'gal'), ('fl_oz', 'fl_oz'), ('ft3', 'ft3')], default='L', max_length=5)),
                ('default_temperature_uom', models.CharField(choices=[('celsius', 'celsius'), ('fahrenheit', 'fahrenheit')], default='celsius', max_length=10)),
                ('default_area_uom', models.CharField(choices=[('m2', 'm2'), ('ft2', 'ft2'), ('hectare', 'hectare'), ('acre', 'acre')], default='m2', max_length=10)),
                ('fiscal_year_start_month', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('fiscal_year_start_day', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('fiscal_calendar_type', models.CharField(choices=[('standard', 'standard'), ('445_week', '445_week'), ('454_week', '454_week'), ('544_week', '544_week')], default='standard', max_length=10)),
                ('cost_method', models.CharField(choices=[('standard', 'standard'), ('average', 'average'), ('fifo', 'fifo')], default='average', max_length=10)),
                ('tax_inclusive_pricing', models.BooleanField(default=False)),
                ('default_document_language', models.CharField(default='en', max_length=10)),
                ('default_paper_size', models.CharField(choices=[('A4', 'A4'), ('letter', 'letter'), ('legal', 'legal')], default='A4', max_length=10)),
                ('text_direction', models.CharField(choices=[('ltr', 'ltr'), ('rtl', 'rtl')], default='ltr', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
                'db_table': 'company_settings',
            },
        ),
    ]
