# Generated by Django 5.2.12 on 2026-04-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='cash_rounding_increment',
            field=models.DecimalField(decimal_places=2, default='0.01', max_digits=4),
        ),
    ]
