# Generated by Django 5.2.12 on 2026-04-05 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_companysettings_cash_rounding_increment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysettings',
            name='multi_currency_enabled',
        ),
    ]
