# Generated by Django 5.2.12 on 2026-04-05 11:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_companysettings_multi_currency_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active_mode', models.CharField(default='light', help_text='Selected preset name (e.g. light, dark, ocean, forest).', max_length=20)),
                ('tokens_by_mode', models.JSONField(blank=True, default=dict, help_text='Per-mode token overrides. Keys are preset names; values are full ThemeTokens objects for that mode. Only modes that have been customized are present.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Theme',
                'verbose_name_plural': 'Company Theme',
                'db_table': 'company_theme',
            },
        ),
    ]
