# Generated by Django 5.2.12 on 2026-04-05 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_companytheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=3, default='0.000', help_text='Default tax percentage applied across the system (0–100).', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='tax_label',
            field=models.CharField(default='Tax', help_text='Local name for tax (VAT, GST, Sales Tax, IVA, etc.).', max_length=20),
        ),
    ]
