# Generated by Django 5.2.12 on 2026-04-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_companysettings_default_tax_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='default_ui_language',
            field=models.CharField(default='en', help_text='Default interface language for users in this organization.', max_length=10),
        ),
    ]
