# Generated by Django 5.2.12 on 2026-03-29 18:47

import apps.organizations.models.organization
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Legal or display name of the organization.', max_length=255)),
                ('slug', models.SlugField(help_text='URL-safe identifier. Lowercase alphanumeric and hyphens only.', max_length=63, unique=True, validators=[apps.organizations.models.organization.validate_org_slug])),
                ('db_name', models.CharField(editable=False, help_text='PostgreSQL database name for this organization.', max_length=63, unique=True)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended'), ('deactivated', 'Deactivated')], db_index=True, default='trial', max_length=20)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code.', max_length=2)),
                ('timezone', models.CharField(default='UTC', help_text='IANA timezone identifier.', max_length=50)),
                ('base_currency', models.CharField(default='USD', help_text='ISO 4217 currency code.', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organizations_organization',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive members lose access but the record is preserved.')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
            ],
            options={
                'db_table': 'organizations_membership',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['slug'], name='organizatio_slug_048085_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['status'], name='organizatio_status_295901_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['created_by'], name='organizatio_created_748a25_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'is_active'], name='organizatio_user_id_9eceb5_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['organization', 'is_active'], name='organizatio_organiz_e0cddf_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='unique_user_per_organization'),
        ),
    ]
