# Generated by Django 5.2.12 on 2026-04-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID for this organization.', max_length=255),
        ),
    ]
