# Generated by Django 5.2.12 on 2026-04-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, help_text='Diagnostic timestamp of first successful submission. Not the gate.', null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='onboarding_form_version_at_completion',
            field=models.PositiveIntegerField(blank=True, help_text='OnboardingForm.version the user last cleared. Diagnostic only.', null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='requires_onboarding',
            field=models.BooleanField(default=True, help_text='True when the user is missing at least one currently-required onboarding field.'),
        ),
    ]
